name: Check name test

on:
  pull_request_target:
    types: [labeled]

jobs:
  a:
    name: ${{ 'analyze' }}
    if: github.event.label.name == 'open source'
    runs-on: ubuntu-latest
    steps:
      - run: echo a
  b:
    name: apply${{ '' }}
    if: github.event.label.name == 'open source'
    runs-on: ubuntu-latest
    steps:
      - run: echo b
  c:
    name: ${{ 'record-error' || 'skipped' }}
    if: github.event.label.name == 'open source'
    runs-on: ubuntu-latest
    steps:
      - run: echo c
